# Generated by Django 2.2.6 on 2019-12-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Fantasy', 'Fantasy'), ('Self-Help', 'Self-Help'), ("Children's", "Children's"), ('Textbook', 'Textbook')], default='Fiction', max_length=20),
        ),
    ]
