# Generated by Django 2.2.6 on 2019-12-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20191219_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='line_total',
            field=models.IntegerField(default=10),
        ),
    ]
