# Generated by Django 2.2.6 on 2019-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20191222_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='line_total',
            field=models.IntegerField(default=10),
        ),
    ]
