# Generated by Django 2.2.6 on 2019-12-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_cart_line_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='line_total',
        ),
    ]
