# Generated by Django 2.2.6 on 2019-12-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_remove_cart_line_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersData',
        ),
    ]
